#!/usr/bin/env node
// item-catalog.mjs — every item in FF1, FF2 and FF3, from each ROM's own tables.
//
// The shop decodes (`lib/ff1-shops.mjs`, `ff2-shops.mjs`, `ff3-shops.mjs`) each
// found a name table and, for two of the three, a price table. This walks those
// over the WHOLE id space rather than just the ids a shop happens to stock.
//
//   node tools/item-catalog.mjs            # writes docs/FF{1,2,3}-ITEMS.md
//   node tools/item-catalog.mjs --game 1 --stdout
//
// ⛔ FF1's table is a general NAME table, not an item table: past the equipment
// it holds class names (RedWiz, Wh.Wiz) and stat labels (HP, ST, PO). Only the
// ids with a nonzero price are goods, and that is stated rather than trimmed
// away silently.
// ⛔ FF2 has NO global price table. A price is a per-shop-entry CODE, so the
// same item can cost different amounts in different shops — the catalog lists
// which shops stock it and for how much, which is the only truthful answer.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import * as F1 from './lib/ff1-text.mjs';
import * as S1 from './lib/ff1-shops.mjs';
import * as F2 from './lib/ff2-text.mjs';
import * as S2 from './lib/ff2-shops.mjs';
import { romaji } from './lib/romaji.mjs';

const { glyph: g3 } = await import('./lib/ff3-text.mjs');
const S3 = await import('./lib/ff3-shops.mjs');

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.join(HERE, '..', 'docs');
const args = process.argv.slice(2);
const flag = (n, d) => { const i = args.indexOf('--' + n); return i < 0 ? d : args[i + 1]; };
const ONLY = flag('game', null);
const STDOUT = args.includes('--stdout');

const ROM1 = new Uint8Array(fs.readFileSync(process.env.FF1_ROM || '/home/joeltco/roms/ff1-usa.nes'));
const ROM2 = new Uint8Array(fs.readFileSync(process.env.FF2_ROM || '/home/joeltco/roms/ff2-jp.nes'));
const ROM3 = new Uint8Array(fs.readFileSync(
  process.env.FF3_ROM || new URL('../FF3-English.nes', import.meta.url).pathname));

/** Contiguous runs of ids, for describing a range without listing 200 numbers. */
function runsOf(ids) {
  if (!ids.length) return '';
  const runs = [];
  let cur = [ids[0]];
  for (let i = 1; i < ids.length; i++) {
    if (ids[i] === ids[i - 1] + 1) cur.push(ids[i]);
    else { runs.push(cur); cur = [ids[i]]; }
  }
  runs.push(cur);
  return runs.map(r => r.length === 1
    ? `\`0x${r[0].toString(16).padStart(2, '0')}\``
    : `\`0x${r[0].toString(16).padStart(2, '0')}\`-\`0x${r[r.length - 1].toString(16).padStart(2, '0')}\``
  ).join(', ');
}

// ── FF1 ─────────────────────────────────────────────────────────────────────
function ff1() {
  const rows = [];
  for (let id = 0; id < 256; id++) {
    rows.push({ id, name: S1.itemName(ROM1, id, F1.glyph), price: S1.itemPrice(ROM1, id) });
  }
  const priced = rows.filter(r => r.price > 0);
  const L = [];
  L.push('# FF1 — every name in the item table');
  L.push('');
  L.push('Generated by `tools/item-catalog.mjs` from the tables decoded in');
  L.push('`tools/lib/ff1-shops.mjs` (pinned by `tools/check-ff1-shops.mjs`).');
  L.push('');
  L.push(`Name pointers: bank 10 \`$B700\`, file \`0x${S1.NAME_PTR_TABLE.toString(16)}\`, 2 bytes LE per id,`);
  L.push('pointing at a `00`-terminated string.  ');
  L.push(`Prices: bank 13 \`$BC00\`, file \`0x${S1.PRICE_TABLE.toString(16)}\`, 2 bytes LE per id.`);
  L.push('');
  L.push('⛔ This is a general NAME table, not an item table. Past the equipment it');
  L.push('holds class names (`RedWiz`, `Wh.Wiz`) and stat labels (`HP`, `ST`, `PO`).');
  L.push(`**${priced.length} of ${rows.filter(r => r.name).length} named ids carry a nonzero price** — those are the goods:`);
  L.push(runsOf(priced.map(r => r.id)) + '.');
  L.push('');
  L.push('| id | name | price |');
  L.push('|---|---|---|');
  for (const r of rows) {
    if (!r.name) continue;
    L.push(`| \`0x${r.id.toString(16).padStart(2, '0')}\` | ${r.name} | ${r.price ? r.price + ' G' : '—'} |`);
  }
  L.push('');
  return L.join('\n');
}

// ── FF2 ─────────────────────────────────────────────────────────────────────
function ff2() {
  // which shops stock each item, and for how much
  const sold = new Map();
  for (const s of S2.allShops(ROM2, F2.glyph)) {
    for (const it of s.items) {
      if (!sold.has(it.id)) sold.set(it.id, []);
      sold.get(it.id).push({ shop: s.index, price: it.price });
    }
  }
  const rows = [];
  for (let id = 0; id < 256; id++) {
    const name = S2.itemName(ROM2, id, F2.glyph);
    if (!name) continue;
    rows.push({ id, name, sold: sold.get(id) || [] });
  }
  const L = [];
  L.push('# FF2 — every name in the item table');
  L.push('');
  L.push('Generated by `tools/item-catalog.mjs` from the tables decoded in');
  L.push('`tools/lib/ff2-shops.mjs` (pinned by `tools/check-ff2-shops.mjs`).');
  L.push('');
  L.push(`Name pointers: bank 10 \`$8200\`, file \`0x${S2.NAME_PTR_TABLE.toString(16)}\`, 2 bytes LE per id,`);
  L.push('pointing at `[icon byte][name][00]`.');
  L.push('');
  L.push('⛔ **FF2 has no global price table.** A price is a per-shop-entry CODE');
  L.push(`(second byte of each entry) resolved through bank 14 \`$8000\`, file`);
  L.push(`\`0x${S2.PRICE_TABLE.toString(16)}\`. So an item does not have "a price" — it has a price`);
  L.push('*in a given shop*. The last column lists every shop that stocks it.');
  L.push('');
  L.push('| id | name | romaji | sold in |');
  L.push('|---|---|---|---|');
  for (const r of rows) {
    const where = r.sold.length
      ? r.sold.map(s => `shop ${s.shop} @ ${s.price} G`).join('<br>')
      : '—';
    L.push(`| \`0x${r.id.toString(16).padStart(2, '0')}\` | ${r.name} | ${romaji(r.name)} | ${where} |`);
  }
  L.push('');
  return L.join('\n');
}

// ── FF3 ─────────────────────────────────────────────────────────────────────
function ff3() {
  const rows = [];
  for (let id = 0; id < 256; id++) {
    rows.push({ id, name: S3.itemName(ROM3, id, g3), price: S3.priceForItem(ROM3, id) });
  }
  const priced = rows.filter(r => r.price > 0);
  const L = [];
  L.push('# FF3 — every name in the item table');
  L.push('');
  L.push('Generated by `tools/item-catalog.mjs` from the tables decoded in');
  L.push('`tools/lib/ff3-shops.mjs` (pinned by `tools/check-ff3-shops.mjs`).');
  L.push('');
  L.push(`Name pointers: bank 24 \`$8800\`, file \`0x${S3.NAME_PTR_TABLE.toString(16)}\`, 2 bytes LE per id,`);
  L.push('pointing at `[icon byte][name][00]` in bank 30 at `$C000`.  ');
  L.push(`Prices: bank 16 \`$9E00\`, file \`0x${S3.PRICE_TABLE.toString(16)}\`, 2 bytes LE per id.`);
  L.push('');
  L.push(`**${priced.length} ids carry a nonzero price.**`);
  L.push('');
  L.push('⛔ Some glyph bytes have no entry in the decoder, so a few names read short');
  L.push('(`Bzzard` for Blizzard). The running game draws the same gap as a space, so');
  L.push('this is the decoder\'s table being incomplete, not the ROM.');
  L.push('');
  L.push('⛔ Eight ids are NOT items: their name pointers land on junk and the game');
  L.push('draws no row for them at all (measured — `item-verify.mjs --game 3 --batch 1`).');
  L.push('`0x00` is the record terminator, so it can never be stocked either way.');
  L.push('They are marked below.');
  L.push('');
  L.push('| id | name | price |');
  L.push('|---|---|---|');
  for (const r of rows) {
    if (!r.name) continue;
    const junk = S3.NON_ITEM_IDS.includes(r.id);
    L.push(`| \`0x${r.id.toString(16).padStart(2, '0')}\` | ${junk ? '_(not an item)_' : r.name} | ${junk ? '—' : (r.price ? r.price + ' G' : '—')} |`);
  }
  L.push('');
  return L.join('\n');
}

const GAMES = { 1: ['FF1-ITEMS.md', ff1], 2: ['FF2-ITEMS.md', ff2], 3: ['FF3-ITEMS.md', ff3] };
for (const [n, [file, fn]] of Object.entries(GAMES)) {
  if (ONLY && ONLY !== n) continue;
  const md = fn();
  if (STDOUT) process.stdout.write(md);
  else {
    fs.writeFileSync(path.join(DOCS, file), md);
    console.log(`wrote docs/${file} (${md.split('\n').filter(l => l.startsWith('| `0x')).length} entries)`);
  }
}
