#!/usr/bin/env node
// script-catalog.mjs — each game's whole script, committed as a document.
//
// The three decoders are already verified against the running game and pinned by
// `check-ff12-text.mjs` and `check-npc-dialogue.mjs`. They existed only as
// dump tools, so the scripts were never actually written down anywhere.
//
//   node tools/script-catalog.mjs
//   node tools/script-catalog.mjs --game 2 --stdout
//
// ⛔ FF2's sub-0x8A dictionary is NOT decoded, so roughly a fifth of each JP
// line comes back as `{xx}`. Those are printed as-is and never guessed — the
// gaps are the honest state of the decode, not noise to be smoothed over.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.join(HERE, '..', 'docs');
const args = process.argv.slice(2);
const flag = (n, d) => { const i = args.indexOf('--' + n); return i < 0 ? d : args[i + 1]; };
const ONLY = flag('game', null);
const STDOUT = args.includes('--stdout');

const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\r?\n/g, ' / ').trim();

async function ff1() {
  const { loadRom, decodeString } = await import('./lib/ff1-text.mjs');
  const rom = loadRom(process.env.FF1_ROM || '/home/joeltco/roms/ff1-usa.nes');
  const rows = [];
  for (let id = 0; id < 0x200; id++) {
    const t = decodeString(rom, id, { nl: ' / ' }).replace(/\s+/g, ' ').trim();
    if (t) rows.push({ id, t });
  }
  const L = ['# FF1 — the script', '',
    'Generated by `tools/script-catalog.mjs`. The decoder is pinned by',
    '`tools/check-ff12-text.mjs`, which checks it against text read off the',
    'running game (FF1\'s DTE halves are REVERSED, which is what that gate holds',
    'in place).', '',
    `${rows.length} strings.`, '', '| id | text |', '|---|---|'];
  for (const r of rows) L.push(`| \`0x${r.id.toString(16).padStart(3, '0')}\` | ${esc(r.t)} |`);
  L.push('');
  return ['FF1-SCRIPT.md', L.join('\n'), rows.length];
}

async function ff2() {
  const F2 = await import('./lib/ff2-text.mjs');
  const rom = new Uint8Array(fs.readFileSync(process.env.FF2_ROM || '/home/joeltco/roms/ff2-jp.nes'));
  const rows = [];
  for (const [label, table] of [['dialogue', F2.DIALOGUE_TABLE], ['hi', F2.DIALOGUE_TABLE_HI]]) {
    for (let id = 0; id < 0x100; id++) {
      let t;
      try { t = F2.decodeLine(rom, id, { table, nl: ' / ' }).replace(/\s+/g, ' ').trim(); } catch { t = ''; }
      if (t && /[ぁ-んァ-ヶ一-龠]/.test(t)) rows.push({ label, id, t });
    }
  }
  const L = ['# FF2 (JP) — the script, as far as it decodes', '',
    'Generated by `tools/script-catalog.mjs`. The kana tables are measured and',
    'pinned by `tools/check-ff12-text.mjs`.', '',
    '⛔ FF2\'s sub-`0x8A` dictionary is **not decoded**, so roughly a fifth of each',
    'line comes back as `{xx}`. Those are printed exactly as they are and never',
    'guessed. FF2 has no dictionary in the FF1 sense — sub-`0x8A` codes are',
    'dakuten kana blocks, and the rest is still open.', '',
    `${rows.length} strings across both tables.`, '',
    '| table | id | text |', '|---|---|---|'];
  for (const r of rows) L.push(`| ${r.label} | \`0x${r.id.toString(16).padStart(2, '0')}\` | ${esc(r.t)} |`);
  L.push('');
  return ['FF2-SCRIPT.md', L.join('\n'), rows.length];
}

async function ff3() {
  const { loadRom, decodeString } = await import('./lib/ff3-text.mjs');
  const rom = loadRom(process.env.FF3_ROM || new URL('../FF3-English.nes', import.meta.url).pathname);
  const rows = [];
  for (let id = 0; id <= 0x3FF; id++) {
    const t = decodeString(rom, id, { nl: ' / ' }).replace(/\s+/g, ' ').trim();
    if (t) rows.push({ id, t });
  }
  const L = ['# FF3 — the script', '',
    'Generated by `tools/script-catalog.mjs`. The DTE table at `0x75FA1` is TWO',
    'PARALLEL arrays, and the decoder is pinned by `tools/check-npc-dialogue.mjs`.', '',
    '⛔ Which NPC says which string is a per-NPC byte in RAM (`$0740,X`), not',
    'arithmetic on the npc id — `stringId = npcId + 0x202` is a description of what',
    'the table happens to contain, with a measured counterexample (Ur 10,28).', '',
    `${rows.length} strings.`, '', '| id | text |', '|---|---|'];
  for (const r of rows) L.push(`| \`0x${r.id.toString(16).padStart(3, '0')}\` | ${esc(r.t)} |`);
  L.push('');
  return ['FF3-SCRIPT.md', L.join('\n'), rows.length];
}

const GAMES = { 1: ff1, 2: ff2, 3: ff3 };
for (const [n, fn] of Object.entries(GAMES)) {
  if (ONLY && ONLY !== n) continue;
  const [file, md, count] = await fn();
  if (STDOUT) process.stdout.write(md);
  else { fs.writeFileSync(path.join(DOCS, file), md); console.log(`wrote docs/${file} (${count} strings)`); }
}
